### ISSUE TITLE
Oracle bug 5733472 “WRONG OUTPUT IN APEX WHEN USING GLOBAL CONTEXT.”

### ISSUE THREAD

**Issue by tmuth** [tmuth/Logger---A-PL-SQL-Logging-Utility#15]
Mark Wagoner posted this on my blog here: http://tylermuth.wordpress.com/2011/11/09/logger-project-moved-temporarilly/#comment-3565

Not sure if it's really an issue and what versions of logger and APEX are impacted, but it sounds troublesome. 

>
I was also having issues regarding Oracle bug 5733472 “WRONG OUTPUT IN APEX WHEN USING GLOBAL CONTEXT.” I noticed the values were not coming from the context when accessed through APEX, although it worked fine using SQL*Plus or SQL Developer. Have you seen this issue as well? We are on an old version of Apex (4.0) so it could be due to that.
<

**Comment by martindsouza** [comment]
This issue was moved to OraOpenSource/Logger#1

**Comment by martindsouza** [comment]
This issue was moved to OraOpenSource/Logger#15
