### ISSUE TITLE
Substitution Strings 

### ISSUE THREAD

**Issue by martindsouza** [tmuth/Logger---A-PL-SQL-Logging-Utility#32]
Thanks to John Scott for this idea.

Would like the ability to support substitution strings. For example: "Updated %num_rows% in table out of %total_rows%".

John and I discussed possible implementation options. For now here's what is purposed:

- Add a new parameter call p_do_substitutions default false
- If user sets p_do_substitutions to true then it will leverage the p_params option for substitution switching rather than logging paramers

Ex:

```sql
logger.append_param(l_params, 'p_empno', p_empno);
logger.log('Employee %P_EMPNO%', p_params => l_params, p_do_substitutions => true)
```

Alternatively, instead of p_do_substitutions we can us p_param_type with 'DEFAULT'/'PARAMS' and 'SUBSTITUTION' (or something like that). We can create global constants to manage. This may be the better option.

**Comment by goodwish** [comment]
Howdy,

When will we get this feature ? Is there an estimate ?

Or, can I contribute on it?

Thanks,
Charlie 木匠 | Database Architect Developer

**Comment by martindsouza** [comment]
This issue was moved to OraOpenSource/Logger#32
