### ISSUE TITLE
Log CURRENT_SCHEMA

### ISSUE THREAD

**Issue by patrickjolliffe** [tmuth/Logger---A-PL-SQL-Logging-Utility#34]
For some scheduled tasks we use external authentication to call the same stored procedure defined on multiple schemas (ie phtutl.purge_pkg.purge, thtutl.purge_pkg.purge).
For current logging version, it is not easy to see which of the stored procedures is being called, because the username field is populated with the external username, OS$ORACLE, only.
I think it may be useful to have an additional field (schema_name?) which is populated with the value of "SYS_CONTEXT ('USERENV', 'CURRENT_SCHEMA')".
Note not a huge deal for us, as we have configured the dbms_application_info action field in our calling process, and also can infer from the UNIT_NAME field.

**Comment by martindsouza** [comment]
This issue was moved to OraOpenSource/Logger#34
