### ISSUE TITLE
select privilege against logger_logs table

### ISSUE THREAD

**Issue by hkpatv** [tmuth/Logger---A-PL-SQL-Logging-Utility#35]
In the sample code, scope is defined by accessing using logger_logs.scope%TYPE.  To be able to access this, then user has to be given SELECT privilege against logger_logs table.  If this is the case, then that user can see all logs for other users.  
Not sure if there is a way to encapsulate the scope data-type into the logger package, that way user doesn't need to be given access to read log tables unless we decide to grant it.  I can't think of a neat way to do this.
It may be a partial solution, although maybe complicated, to perform row-level-security against the logger_logs table, so that non-priviledged users can only see logs that they have created.

**Comment by martindsouza** [comment]
This issue was moved to OraOpenSource/Logger#36
