### ISSUE TITLE
Reference to BI_LOGGER_LOGS

### ISSUE THREAD

**Issue by casajarm** [tmuth/Logger---A-PL-SQL-Logging-Utility#36]
In the script LOGGER_INSTALL.SQL the trigger BI_LOGGER_LOGS is dropped but then in the procedure LOGGER_CONFIGURE it is compiled resulting in an error:

Calling logger_configure begin * ERROR at line 1: ORA-04080: trigger 'BI_LOGGER_LOGS' does not exist ORA-06512: at "LOGGER_USER.LOGGER_CONFIGURE", line 108 ORA-06512: at line 2

**Comment by casajarm** [comment]
Sorry this was over a year ago. I should have noted it at the time.

**Comment by martindsouza** [comment]
This issue was moved to OraOpenSource/Logger#37
