### ISSUE TITLE
More fine grained control for log_apex_items() 

### ISSUE THREAD

**Issue by shakerlxxv** [tmuth/Logger---A-PL-SQL-Logging-Utility#53]
For larger APEX apps, the current behavior of log_apex_items to log all the application items as well as all page items results in a large number of records being written to logger_logs_apex_items. 

Here are a few options which could be considered to enable more fine grained control over the results of log_apex_items call.

* Separate the application items and the page items, perhaps log one or both.
* By default limit the page items being logged to the current APEX page ( APP_PAGE_ID )
* Only log items with non-NULL values

**Comment by martindsouza** [comment]
This issue was moved to OraOpenSource/Logger#54
