### ISSUE TITLE
@logger_no_op has compilation errors

### ISSUE THREAD

**Issue by stephane303** [tmuth/Logger---A-PL-SQL-Logging-Utility#57]
Under oracle 11gR2 i get the followings for the package body:
(in french sorry, but it means the function haven't been defined in the boy ...)

[Error] PLS-00323 (81: 13): PLS-00323: Sous-programme ou curseur 'LOG_PERMANENT' déclaré dans les spécifications; doit être défini dans le corps.
[Error] PLS-00323 (87: 13): PLS-00323: Sous-programme ou curseur 'LOG_WARNING' déclaré dans les spécifications; doit être défini dans le corps.
[Error] PLS-00323 (93: 13): PLS-00323: Sous-programme ou curseur 'LOG_INFORMATION' déclaré dans les spécifications; doit être défini dans le corps.
[Error] PLS-00323 (99: 13): PLS-00323: Sous-programme ou curseur 'LOG' déclaré dans les spécifications; doit être défini dans le corps.
[Error] PLS-00323 (218: 12): PLS-00323: Sous-programme ou curseur 'OK_TO_LOG' déclaré dans les spécifications; doit être défini dans le corps.
[Error] PLS-00323 (221: 13): PLS-00323: Sous-programme ou curseur 'INS_LOGGER_LOGS' déclaré dans les spécifications; doit être défini dans le corps.

**Comment by martindsouza** [comment]
This issue was moved to OraOpenSource/Logger#58
