### ISSUE TITLE
logger vs debugf

### ISSUE THREAD

**Issue by database-craftsman** [tmuth/Logger---A-PL-SQL-Logging-Utility#58]
We have been with debug.f for 5 years. There 2 good features that logger doesn't have.
1. tail -f debug_trace_file.
2. debug.f("%s rows update on table %s", l_count, l_table_name);

As C printf: It can optionally contain embedded format specifiers that are replaced by the values specified in subsequent additional arguments and formatted as requested.

Below code with logger to print local variables is awkward, it's not as flexible as debug.f("%s",l_abc). when I want to print different set of variables at each time, I have to add and delete some elements in array l_params.

logger.append_param(l_params, 'p_param1_todo',p_param1_todo);
logger.log('START', l_scope, null, l_params);

There is some workaround for "tail -f".

Can we add feature of replacing print variable like printf("%s",l_abc) to next release?

This feature request is same as issues 32, Substitution Strings :
https://github.com/tmuth/Logger---A-PL-SQL-Logging-Utility/issues/32

C printf format is easier to use, better than logger.log('Employee %P_EMPNO%', p_params => l_params, p_do_substitutions => true). Less code.   ^_^

Thanks,
Charlie

**Comment by martindsouza** [comment]
This issue was moved to OraOpenSource/Logger#59
