### ISSUE TITLE
Seperate admin calls into seperate package

### ISSUE THREAD

**Issue by patrickjolliffe** [tmuth/Logger---A-PL-SQL-Logging-Utility#59]
We have logger installed into dedicated schema (UTL_LOGGER), and have locked this schema for security.  I believe my options for changing settings (via logger.set_level) are as follows:
1) For every change required, unlock UTL_LOGGER, login as that user, make the change, log out and then relock the user.  Note, this is quite a lot of manual effort and leaves open the possibility of errors (forget to relock the user)
2) Use the PROTECT_ADMIN_PROCS options to allow all users to make changes via logger.set_level.  This is not ideal, as logger mechanism is entirely unsecured, all users can make changes.

Suggest a better way would be to separate the admin functions into a seperate package (LOGGER_CONFIG/LOGGER_ADMIN/????).  Execute permission could then be granted or revoked on this package using standard Oracle security.  I think in that case, the PROTECT_ADMIN_PROCS mechanism could be removed, simplifying the code.

**Comment by martindsouza** [comment]
This issue was moved to OraOpenSource/Logger#60
