### ISSUE TITLE
Add session id to logged values

### ISSUE THREAD

**Issue by jhodge8** [tmuth/Logger---A-PL-SQL-Logging-Utility#64]
Could we log the session id (new column) along with other information?

This would provide easy filtering of logs spanning different values for scope and within a single user.  It also helps pick apart activity if there are multiple sessions concurrently running the same set of code.

Once you've identified your starting point in the log, pulling out the complete history of the session is easily done.

It's hopefully a quick-and-easy step to add the detail into ins_logger_logs.

**Comment by martindsouza** [comment]
This issue was moved to OraOpenSource/Logger#65

**Comment by martindsouza** [comment]
New column sid added which will always be populated
