### ISSUE TITLE
Indent and timing Problem

### ISSUE THREAD

**Issue by B0N3** [tmuth/Logger---A-PL-SQL-Logging-Utility#72]
In "procedure time_stop" ~line 1003 the timer is deleted and g_running_timers decremented (this already happend in the function called in ~line 997).

The second bug that occurred on my end is tied to time zones. In "FUNCTION time_stop" the time delta was always off by 2 hours. My solution was saving the timestamp in a variable before using it to calculate the difference. I guess the same thing will be true for "FUNCTION time_stop_seconds", but i had no time testing it.

I am using the latest stable version 2.1.2

**Comment by martindsouza** [comment]
This issue was moved to OraOpenSource/Logger#73
