### ISSUE TITLE
logger_install generates error 

### ISSUE THREAD

**Issue by iloon** [tmuth/Logger---A-PL-SQL-Logging-Utility#73]
SP2-0734: unknown command beginning "<span id="..." - rest of line ignored.
SP2-0734: unknown command beginning "<span id="..." - rest of line ignored.
SP2-0734: unknown command beginning "<span id="..." - rest of line ignored.
SP2-0734: unknown command beginning "<span id="..." - rest of line ignored.
SP2-0044: For a list of known commands enter HELP
and to leave enter EXIT.
SP2-0734: unknown command beginning "<span id="..." - rest of line ignored.
SP2-0734: unknown command beginning "<span id="..." - rest of line ignored.
SP2-0734: unknown command beginning "<span id="..." - rest of line ignored.
SP2-0734: unknown command beginning "<span id="..." - rest of line ignored.
SP2-0044: For a list of known commands enter HELP
and to leave enter EXIT.

**Comment by martindsouza** [comment]
This issue was moved to OraOpenSource/Logger#74
