### ISSUE TITLE
time zone inconsistency timers

### ISSUE THREAD

**Issue by tomvdduin** [tmuth/Logger---A-PL-SQL-Logging-Utility#74]
the type ts_array is a table of timestamp. But the procedures time_start and time_stop uses systimestamp; that has a time zone specified. I am at GMT+2, and regularly have something like this in the logger table:
START: test
STOP : test- 01:59:59.969

So the ts_array shold be defined by timestamp with time zone or you should use localtimestamp instead of systimestamp

**Comment by martindsouza** [comment]
This issue was moved to OraOpenSource/Logger#75
