### ISSUE TITLE
ORA-06508: PL/SQL: could not find program unit being called while calling Logger.

### ISSUE THREAD

**Issue by sChintamani** [tmuth/Logger---A-PL-SQL-Logging-Utility#75]
Hi,
First off, thanks a bunch for wriring an excellent utility for logging PLSQL code.  

We included PLSQL Logger in our DEV instance and we are observing that it is throwing ORA-06508: PL/SQL: could not find program unit being called seemingly at random.  This is very specifically happening after new deployments.  The issue goes away by itself without recompiling anything in the schema.

Any ideas on what might be causing this?

**Comment by martindsouza** [comment]
This issue was moved to OraOpenSource/Logger#76
