### ISSUE TITLE
NO_OP installer has references to logger_logs table

### ISSUE THREAD

**Issue by sChintamani** [tmuth/Logger---A-PL-SQL-Logging-Utility#77]
Hi,
The _no_op_ installer has anchored references to logger_logs table.  This I found the hard way, once the script went to deployment into near PROD env.  

We installed the **regular** version in DEV & QA environments and no_op version was required on the PROD env.  When we ran the no_op version without un-installing the previous logger, the builds went fine and we didn't realize this anchoring until we hit PROD.  I just now came back from this deployment (it's _*3:00 AM*_ in the morning :( !)..  Please see the attached screen-shot for details.

Would be nice to have an updated script checked in into git-hub.  I 'll be more than happy to contribute the updated version, we came up with.

![image](https://cloud.githubusercontent.com/assets/8726936/4380166/3e38904a-4367-11e4-8547-8c979ac6f499.png)

**Comment by martindsouza** [comment]
This issue was moved to [OraOpenSource/Logger#78](https://github.com/OraOpenSource/Logger/issues/78)
