### ISSUE TITLE
Look at removing dependency on CREATE ANY CONTEXT requirement

### ISSUE THREAD

**Issue by martindsouza** [tmuth/Logger---A-PL-SQL-Logging-Utility#81]
We may not be able to do this due to performance issues but worth looking into (or at least offering it as an option with the notation that performance may be impacted).

**Comment by rimblas** [comment]
I think it's well worth exploring and allowing it as an option for those hosted environments where CREATE ANY CONTEXT is just not possible.

**Comment by martindsouza** [comment]
This issue was moved to OraOpenSource/Logger#82
